baseURL = "http://localhost:1313/"
title = "selene"
description = "selene power by hugo."
languageCode = "en-us"

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true  # # Allow raw HTML in Markdown

[params]
  theme = "toggle"              # light, dark, auto, toggle
  toc = true                    # enable table of contents
  mathjax = true                # enable mathjax
  
  # Theme Settings
  [[params.menu]]
    name = "/posts"
    url = "/posts"
    weight = 1
  [[params.menu]]
    name = "/projects"
    url = "/projects"
    weight = 2
  [[params.menu]]
    name = "/about"
    url = "/about"
    weight = 3
  [[params.menu]]
    name = "/notes"
    url = "/notes"
    weight = 4
  
  # menu configuration
  [[params.social]]
    name = "github"
    url = ""
    icon = "github"
  [[params.social]]
    name = "email"
    url = "mailto:"
    icon = "email"
  [[params.social]]
    name = "twitter"
    url = ""
    icon = "twitter"
  [[params.social]]
    name = "rss"
    url = "/index.xml"
    icon = "rss"

  # gitalk
  [params.gitalk]           
  owner = ""             
  repo = ""              
  clientId = ""           
  clientSecret = ""
